### ISSUE TITLE
Server error (HTTP 500) when accessing `/author`

### ISSUE THREAD

**Issue by MattHeard** [MattHeard/Dendrite#251]

**Comment by MattHeard** [comment]
/author
    java.lang.NullPointerException
    	at com.deuteriumlabs.dendrite.dependencies.DatastoreEntity.getProperty(DatastoreEntity.java:43)
    	at com.deuteriumlabs.dendrite.model.User.getIdFromEntity(User.java:211)
    	at com.deuteriumlabs.dendrite.model.User.readIdFromEntity(User.java:420)
    	at com.deuteriumlabs.dendrite.model.User.readPropertiesFromEntity(User.java:505)
    	at com.deuteriumlabs.dendrite.model.Model.read(Model.java:59)
    	at com.deuteriumlabs.dendrite.view.AuthorView.setId(AuthorView.java:206)
    	at com.deuteriumlabs.dendrite.view.AuthorView.initialise(AuthorView.java:66)
